let itemTypes = [];
function createItemType(obj) {
    itemTypes.push({
        //Required To Fill Out
        type: obj.type, //What the Item is
        keyVSitem: obj.keyVSitem, //If The Item is a key or not a key 
        display: obj.display, //If items keybox displays on left or right side
        
        //Generals
        color: obj.color ? obj.color : 'black', //What Color to display Item
        altName: obj.altName ? obj.altName : false, //What Color to display Item
        colorLB: obj.colorLB ? obj.colorLB : obj.color, //What color to display item on left bar
        canSearch: obj.canSearch ? obj.canSearch : true, //If user can filter search by item type
        searchType: obj.searchType ? obj.searchType : obj.type, //Title when searching for this specific item

        //If showing items in Pull Up Menu
        bladeType: obj.bladeType ? obj.bladeType : false,
        location: obj.location ? obj.location : false,
        itemType: obj.itemType ? obj.itemType : false,
        TLUID: obj.TLUID ? obj.TLUID : false,
        buttons: obj.buttons ? obj.buttons : false,
        battery: obj.battery ? obj.battery : false,
        frequency: obj.frequency ? obj.frequency : false,
        amount: obj.amount ? obj.amount : false,
        chip: obj.chip ? obj.chip : false,
        fccID: obj.fccID ? obj.fccID : false,
        model: obj.model ? obj.model : false,
        link: obj.link ? obj.link : false,
        ourCost: obj.ourCost ? obj.ourCost : false,
        retail: obj.retail ? obj.retail : false,
        photo: obj.photo ? obj.photo : false,
        notes: obj.notes ? obj.notes : false,
        worksOn: obj.worksOn ? obj.worksOn : false,
        goToCCR: obj.goToCCR ? obj.goToCCR : false,
        extraOf: obj.extraOf ? obj.extraOf : false,
    })
}
createItemType({
    type: 'key',
    color: 'black',
    colorLB: 'lightgray',
    keyVSitem: 'key',
    bladeType: true,
    display: 'left',
    location: true,
    TLUID: true,
    buttons: true,
    battery: true,
    frequency: true,
    amount: true,
    chip: true,
    fccID: true,
    model: true,
    link: true,
    ourCost: true,
    retail: true,
    photo: true,
    notes: true,
    worksOn: true,
})
createItemType({
    type: 'remote',
    color: '#008833',
    colorLB: '#65a765',
    keyVSitem: 'item',
    location: true,
    display: 'right',
    buttons: true,
    frequency: true,
    amount: true,
    battery: true,
    fccID: true,
    model: true,
    link: true,
    ourCost: true,
    retail: true,
    photo: true,
    notes: true,
    worksOn: true,
})
createItemType({
    type: 'shell',
    color: 'rgba(255, 234, 0,0.75)',
    keyVSitem: 'key',
    location: true,
    bladeType: true,
    display: 'right',
    buttons: true,
    TLUID: true,
    amount: true,
    model: true,
    link: true,
    ourCost: true,
    retail: true,
    photo: true,
    notes: true,
    worksOn: true,
})
createItemType({
    type: 'shellremote',
    color: 'yellow',
    keyVSitem: 'key',
    searchType: 'Shell Remote',
    location: true,
    bladeType: true,
    display: 'right',
    buttons: true,
    amount: true,
    model: true,
    link: true,
    ourCost: true,
    retail: true,
    photo: true,
    notes: true,
    worksOn: true,
})
createItemType({
    type: 'chip',
    color: '#344',
    colorLB: '#b6c1cb',
    keyVSitem: 'item',
    location: true,
    display: 'right',
    itemType: true,
    amount: true,
    chip: true,
    buttons: true,
    fccID: true,
    model: true,
    link: true,
    ourCost: true,
    retail: true,
    photo: true,
    notes: true,
    worksOn: true,
})
createItemType({
    type: 'blade',
    color: 'white',
    location: true,
    keyVSitem: 'item',
    itemType: true,
    bladeType: true,
    display: 'right',
    buttons: true,
    amount: true,
    model: true,
    link: true,
    ourCost: true,
    retail: true,
    photo: true,
    notes: true,
    worksOn: true,
})
createItemType({
    type: 'extra',
    color: 'black',
    searchType: false,
    canSearch: false,
    location: true,
    keyVSitem: 'item',
    itemType: true,
    photo: true,
    goToCCR: true,
    extraOf: true,
})
createItemType({
    type: 'empty',
    color: 'black',
    searchType: false,
    canSearch: false,
    keyVSitem: 'item',
})
createItemType({
    type: 'pt',
    searchType: 'key',
    altName: 'key',
    colorLB: 'lightgray',
    color: 'black',
    display: 'left',
    bladeType: true,
    keyVSitem: 'key',
    canSearch: true,
    location: true,
    itemType: true,
    buttons: true,
    TLUID: true,
    amount: true,
    chip: true,
    model: true,
    link: true,
    ourCost: true,
    retail: true,
    photo: true,
    notes: true,
    worksOn: true,
})